config/routes.rb
Basl::Application.routes.draw do

  get 'BASLsite_FormReturn' => 'registration_landing_pages#index'

  resources :registration_landing_pages

  resources :registrations

  get 'about_us' => 'about_us#index', as: :about_us

  get 'rankings/edit' => 'rankings#edit', as: :edit_rankings

  resources :rankings

  resources :absences

  get 'next_games' => 'games#next_games', as: :next_games

  post 'photo/:id' => 'teams#update_photo', :as => :update_photo

  get 'games/:id/:team/gamesheet' => 'games#gamesheet', :as => :gamesheet

  get 'soccer_game' => 'soccer#index', :as => :soccer_game

  get 'admin' => 'admin#index', :as => :admin

  get 'administrivia' => 'administrivia#index', :as => :administrivia

  post 'seasons/:id/update_game_duration' => 'games#update_game_duration', :as => :update_game_duration

  post 'seasons/redirect' => 'seasons#redirect', :as => :season_redirect

  resources :commercial_listings

  get 'games/:id/cancel_edit' => 'games#cancel_edit', :as => :cancel_edit

  get 'games/cancel_new' => 'games#cancel_new', :as => :cancel_new

  resources :users

  resources :users

  resources :rules

  resources :pools

  resources :players

  resources :news_bytes

  get 'news_bytes/limit/:limit/offset/:offset' => 'news_bytes#index', :as => :news_page

  resources :game_types

  resources :fields

  resources :seasons do

    resources :rankings

    resources :teams

    resources :games

    resources :standings

  end

  resources :games
  
  resources :standings

  resources :teams

  get 'login' => 'login#index'

  get 'logout' => 'login#logout'

  post 'authenticate' => 'login#authenticate'

  get 'teams/:team_id/photo' => 'teams#photo', :as => :photo

  get 'teams/:team_id/players' => 'players#index', :as => :team_players

  get 'teams/:team_id/new_player' => 'players#new', :as => :new_team_player

  get 'teams/:id/games' => 'teams#games', :as => :team_games

  root :to => "news_bytes#index"

end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController

  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/views/about_us/index.html.erb
<ul class="nostyle">
<% unless @season.nil? or @season.id.nil? %>
<td><%= link_to "Teams", season_teams_path(:season_id => @season.id) %></td>
<% end %>
<li><%= link_to "Seasons", :controller => :seasons %></li>
<li><%= link_to "Fields", fields_path %></li>
<li><%= link_to "Info", administrivia_path %></li>
<li><%= link_to "Rules", rules_path %></li>
<li><%= link_to "GSA Web Site", "http://www.gloucesterhornets.ca/" %></li>
<li><%= link_to "Blackburn Arms Pub", "http://www.blackburnarms.com/" %></li>
<li><%= link_to "Contact Us", "mailto:info@ba-soccer.ca" %></li>
<li><%= link_to "Photos", 'http://hwmgt.smugmug.com/BASL' %></li>
<li><%= link_to "Business directory", commercial_listings_path %></li>
<li><%= link_to "Admin", admin_path %></li>
</ul>