config/routes.rb
Basl::Application.routes.draw do

  get 'BASLsite_FormReturn' => 'registration_landing_pages#index'

  resources :registration_landing_pages

  resources :registrations

  get 'about_us' => 'about_us#index', as: :about_us

  get 'rankings/edit' => 'rankings#edit', as: :edit_rankings

  resources :rankings

  resources :absences

  get 'next_games' => 'games#next_games', as: :next_games

  post 'photo/:id' => 'teams#update_photo', :as => :update_photo

  get 'games/:id/:team/gamesheet' => 'games#gamesheet', :as => :gamesheet

  get 'soccer_game' => 'soccer#index', :as => :soccer_game

  get 'admin' => 'admin#index', :as => :admin

  get 'administrivia' => 'administrivia#index', :as => :administrivia

  post 'seasons/:id/update_game_duration' => 'games#update_game_duration', :as => :update_game_duration

  post 'seasons/redirect' => 'seasons#redirect', :as => :season_redirect

  resources :commercial_listings

  get 'games/:id/cancel_edit' => 'games#cancel_edit', :as => :cancel_edit

  get 'games/cancel_new' => 'games#cancel_new', :as => :cancel_new

  resources :users

  resources :users

  resources :rules

  resources :pools

  resources :players

  resources :news_bytes

  get 'news_bytes/limit/:limit/offset/:offset' => 'news_bytes#index', :as => :news_page

  resources :game_types

  resources :fields

  resources :seasons do

    resources :rankings

    resources :teams

    resources :games

    resources :standings

  end

  resources :games
  
  resources :standings

  resources :teams

  get 'login' => 'login#index'

  get 'logout' => 'login#logout'

  post 'authenticate' => 'login#authenticate'

  get 'teams/:team_id/photo' => 'teams#photo', :as => :photo

  get 'teams/:team_id/players' => 'players#index', :as => :team_players

  get 'teams/:team_id/new_player' => 'players#new', :as => :new_team_player

  get 'teams/:id/games' => 'teams#games', :as => :team_games

  root :to => "news_bytes#index"

end

app/views/admin/index.html.erb
<ul class="nostyle">
<li><%= link_to "Player rankings", rankings_path %></li>
<li><%= link_to "Absences", absences_path %></li>
<% if @logged_in %>
<li><%= link_to "Game Types", game_types_path %></li>
<li><%= link_to "Playoff Pools", pools_path %></li>
<li><%= link_to "Users", users_path %></li>
<% end %>
<% if @logged_in %>
<li><%= link_to "Logout #{@logged_in.name}", logout_path %></li>
<% else %>
<li><%= link_to "Login", login_path %></li>
<% end %>
</ul>