config/routes.rb
Basl::Application.routes.draw do

  get 'BASLsite_FormReturn' => 'registration_landing_pages#index'

  resources :registration_landing_pages

  resources :registrations

  get 'about_us' => 'about_us#index', as: :about_us

  get 'rankings/edit' => 'rankings#edit', as: :edit_rankings

  resources :rankings

  resources :absences

  get 'next_games' => 'games#next_games', as: :next_games

  post 'photo/:id' => 'teams#update_photo', :as => :update_photo

  get 'games/:id/:team/gamesheet' => 'games#gamesheet', :as => :gamesheet

  get 'soccer_game' => 'soccer#index', :as => :soccer_game

  get 'admin' => 'admin#index', :as => :admin

  get 'administrivia' => 'administrivia#index', :as => :administrivia

  post 'seasons/:id/update_game_duration' => 'games#update_game_duration', :as => :update_game_duration

  post 'seasons/redirect' => 'seasons#redirect', :as => :season_redirect

  resources :commercial_listings

  get 'games/:id/cancel_edit' => 'games#cancel_edit', :as => :cancel_edit

  get 'games/cancel_new' => 'games#cancel_new', :as => :cancel_new

  resources :users

  resources :users

  resources :rules

  resources :pools

  resources :players

  resources :news_bytes

  get 'news_bytes/limit/:limit/offset/:offset' => 'news_bytes#index', :as => :news_page

  resources :game_types

  resources :fields

  resources :seasons do

    resources :rankings

    resources :teams

    resources :games

    resources :standings

  end

  resources :games
  
  resources :standings

  resources :teams

  get 'login' => 'login#index'

  get 'logout' => 'login#logout'

  post 'authenticate' => 'login#authenticate'

  get 'teams/:team_id/photo' => 'teams#photo', :as => :photo

  get 'teams/:team_id/players' => 'players#index', :as => :team_players

  get 'teams/:team_id/new_player' => 'players#new', :as => :new_team_player

  get 'teams/:id/games' => 'teams#games', :as => :team_games

  root :to => "news_bytes#index"

end

app/models/commercial_listing.rb
class CommercialListing < ActiveRecord::Base
  validates :company_name, :presence => true, :uniqueness => true
  validates :player_name, :presence => true, :uniqueness => true

  def contact
    contact = []
    if telephone
      contact << "telephone"
    end
    if email
      contact << "email"
    end
    if website
      contact << "website"
    end
    contact
  end
end

app/controllers/commercial_listings_controller.rb
class CommercialListingsController < ApplicationController
  before_action :set_commercial_listing, only: [:show, :edit, :update, :destroy]
  before_action :check_authorization, :except => 'index'

  # GET /commercial_listings
  # GET /commercial_listings.json
  def index
    @commercial_listings = CommercialListing.order(:player_name).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @commercial_listings }
      format.xml { render :xml => @commercial_listings }
    end
  end

  # GET /commercial_listings/1
  # GET /commercial_listings/1.json
  # GET /commercial_listings/1.vcard
  def show
    #@commercial_listing = CommercialListing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @commercial_listing }
      format.vcard # show.vcard.erb
    end
  end

  # GET /commercial_listings/new
  # GET /commercial_listings/new.json
  def new
    @commercial_listing = CommercialListing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @commercial_listing }
    end
  end

  # GET /commercial_listings/1/edit
  def edit
    #@commercial_listing = CommercialListing.find(params[:id])
  end

  # POST /commercial_listings
  # POST /commercial_listings.json
  def create
    @commercial_listing = CommercialListing.new(commercial_listing_params)

    respond_to do |format|
      if @logged_in.update_site? and @commercial_listing.save
        format.html { redirect_to @commercial_listing, :notice => 'Commercial listing was successfully created.' }
        format.json { render :json => @commercial_listing, :status => :created, :location => @commercial_listing }
      else
        format.html { render :action => "new" }
        format.json { render :json => @commercial_listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commercial_listings/1
  # PUT /commercial_listings/1.json
  def update
    #@commercial_listing = CommercialListing.find(params[:id])

    respond_to do |format|
      if @commercial_listing.update_attributes(commercial_listing_params)
        format.html { redirect_to @commercial_listing, :notice => 'Commercial listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @commercial_listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commercial_listings/1
  # DELETE /commercial_listings/1.json
  def destroy
    #@commercial_listing = CommercialListing.find(params[:id])
    @commercial_listing.destroy

    respond_to do |format|
      format.html { redirect_to commercial_listings_url }
      format.json { head :no_content }
    end
  end

  private 
  # Use callbacks to share common setup or constraints between actions.
  def set_commercial_listing
    @commercial_listing = CommercialListing.find(params[:id])
    unless @logged_in.update_site?
      @commercial_listing.readonly!
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def commercial_listing_params
    params.require(:commercial_listing).permit(:id, :company_name, :player_name, :title, :business_type, :telephone, :email, :website, :description)
  end

end

app/helpers/commercial_listings_helper.rb
module CommercialListingsHelper
end

app/views/commercial_listings/_form.html.erb
<%= form_for(@commercial_listing) do |f| %>
  <% if @commercial_listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commercial_listing.errors.count, "error") %> prohibited this commercial_listing from being saved:</h2>

      <ul>
      <% @commercial_listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :player_name %><br />
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :business_type %><br />
    <%= f.text_field :business_type %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commercial_listings/edit.html.erb
<h1>Editing commercial_listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @commercial_listing %> |
<%= link_to 'Back', commercial_listings_path %>

app/views/commercial_listings/index.html.erb
<h1>Business directory</h1>

<table border="0">
<% @commercial_listings.each do |commercial_listing| %>
  <tr>
    <td>
<table border="0" cellspading="0" width="100%">
  <tr>
    <th colspan="2" align="center" class="news_byte_th"><%= commercial_listing.player_name %></th>
  </tr>
  <tr>
    <td class="left_border" width="50%" valign="top">
      <ul>
        <% unless commercial_listing.company_name.empty? %>
          <li><%= commercial_listing.company_name %></li>
        <% end %>
        <% unless commercial_listing.title.empty? %>
          <li><%= commercial_listing.title %></li>
        <% end %>
        <% unless commercial_listing.business_type.empty? %>
          <li><%= commercial_listing.business_type %></li>
        <% end %>
      </ul>
    </td>
    <td class="right_border" width="50%" valign="top">
      <ul>
        <% unless commercial_listing.telephone.empty? %>
          <li>Telephone: <%= commercial_listing.telephone %></li>
        <% end %>
        <% unless commercial_listing.email.empty? %>
          <li>Email: <%= commercial_listing.email %></li>
        <% end %>
        <% unless commercial_listing.website.empty? %>
          <li>Website: <%= link_to commercial_listing.website, commercial_listing.website %></li>
        <% end %>
      </ul>
    </td>
  </tr>
  <tr>
    <td colspan="2" class="sides_and_bottom_border"><%= commercial_listing.description %>
   <br /><br /><%= link_to 'vcard', commercial_listing_path(commercial_listing, :format => :vcard) %>
    </td>
  </tr>
</table>
    </td>
    <% if @logged_in and @logged_in.update_site? %>
    <td><%= link_to 'Show', commercial_listing %></td>
    <td><%= link_to 'Edit', edit_commercial_listing_path(commercial_listing) %></td>
    <td><%= link_to 'Destroy', commercial_listing, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<br />

<% if @logged_in and @logged_in.update_site? %>
<%= link_to_unless @logged_in.nil?, 'New Commercial listing', new_commercial_listing_path %>
<% end %>

app/views/commercial_listings/new.html.erb
<h1>New commercial_listing</h1>

<%= render 'form' %>

<%= link_to 'Back', commercial_listings_path %>

app/views/commercial_listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @commercial_listing.company_name %>
</p>

<p>
  <b>Player name:</b>
  <%= @commercial_listing.player_name %>
</p>

<p>
  <b>Title:</b>
  <%= @commercial_listing.title %>
</p>

<p>
  <b>Business type:</b>
  <%= @commercial_listing.business_type %>
</p>

<p>
  <b>Telephone:</b>
  <%= @commercial_listing.telephone %>
</p>

<p>
  <b>Email:</b>
  <%= @commercial_listing.email %>
</p>

<p>
  <b>Website:</b>
  <%= @commercial_listing.website %>
</p>

<p>
  <b>Description:</b>
  <%= @commercial_listing.description %>
</p>


<%= link_to 'Edit', edit_commercial_listing_path(@commercial_listing) %> |
<%= link_to 'Back', commercial_listings_path %>

app/views/commercial_listings/show.vcard.erb
BEGIN:VCARD
VERSION:4.0
FN: <%= @commercial_listing.player_name %>
ORG:<%= raw @commercial_listing.company_name %>
TITLE:<%= @commercial_listing.title %>
TEL;TYPE="work,voice";VALUE=uri:tel:<%= @commercial_listing.telephone %>
EMAIL:<%= @commercial_listing.email %>
URL:<%= @commercial_listing.website %>
NOTE:<%= @commercial_listing.description %>
REV:<%= @commercial_listing.updated_at.strftime("%Y%m%dT%H%M%SZ") %>
END:VCARD