config/routes.rb
Basl::Application.routes.draw do

  get 'BASLsite_FormReturn' => 'registration_landing_pages#index'

  resources :registration_landing_pages

  resources :registrations

  get 'about_us' => 'about_us#index', as: :about_us

  get 'rankings/edit' => 'rankings#edit', as: :edit_rankings

  resources :rankings

  resources :absences

  get 'next_games' => 'games#next_games', as: :next_games

  post 'photo/:id' => 'teams#update_photo', :as => :update_photo

  get 'games/:id/:team/gamesheet' => 'games#gamesheet', :as => :gamesheet

  get 'soccer_game' => 'soccer#index', :as => :soccer_game

  get 'admin' => 'admin#index', :as => :admin

  get 'administrivia' => 'administrivia#index', :as => :administrivia

  post 'seasons/:id/update_game_duration' => 'games#update_game_duration', :as => :update_game_duration

  post 'seasons/redirect' => 'seasons#redirect', :as => :season_redirect

  resources :commercial_listings

  get 'games/:id/cancel_edit' => 'games#cancel_edit', :as => :cancel_edit

  get 'games/cancel_new' => 'games#cancel_new', :as => :cancel_new

  resources :users

  resources :users

  resources :rules

  resources :pools

  resources :players

  resources :news_bytes

  get 'news_bytes/limit/:limit/offset/:offset' => 'news_bytes#index', :as => :news_page

  resources :game_types

  resources :fields

  resources :seasons do

    resources :rankings

    resources :teams

    resources :games

    resources :standings

  end

  resources :games
  
  resources :standings

  resources :teams

  get 'login' => 'login#index'

  get 'logout' => 'login#logout'

  post 'authenticate' => 'login#authenticate'

  get 'teams/:team_id/photo' => 'teams#photo', :as => :photo

  get 'teams/:team_id/players' => 'players#index', :as => :team_players

  get 'teams/:team_id/new_player' => 'players#new', :as => :new_team_player

  get 'teams/:id/games' => 'teams#games', :as => :team_games

  root :to => "news_bytes#index"

end

app/models/field.rb
class Field < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :code, :presence => true, :uniqueness => true
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_action :check_authorization, :except => ['index', 'show']

  # GET /fields
  # GET /fields.xml
  def index
    @fields = Field.order('name')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fields }
    end
  end

  # GET /fields/1
  # GET /fields/1.xml
  def show
    #@field = Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @field }
    end
  end

  # GET /fields/new
  # GET /fields/new.xml
  def new
    @field = Field.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @field }
    end
  end

  # GET /fields/1/edit
  def edit
    #@field = Field.find(params[:id])
  end

  # POST /fields
  # POST /fields.xml
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @logged_in.update_site and @field.save
        format.html { redirect_to(@field, :notice => 'Field was successfully created.') }
        format.xml  { render :xml => @field, :status => :created, :location => @field }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @field.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fields/1
  # PUT /fields/1.xml
  def update
    #@field = Field.find(params[:id])

    respond_to do |format|
      if @field.update_attributes(field_params)
        format.html { redirect_to(@field, :notice => 'Field was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @field.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.xml
  def destroy
    #@field = Field.find(params[:id])
    @field.destroy

    respond_to do |format|
      format.html { redirect_to(fields_url) }
      format.xml  { head :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @field = Field.find(params[:id])
    unless @logged_in.update_site?
      @field.readonly!
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def field_params
    params.require(:field).permit(:id, :name, :code, :map_url, :location)
  end

end

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :map_url %><br />
    <%= f.text_field :map_url %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<h1>Fields</h1>

<table class="bordered">
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Map</th>
    <th>Location</th>
    <% if @logged_in and @logged_in.update_site? %>
    <th></th>
    <th></th>
    <th></th>
    <% end %>
  </tr>

<% for field in @fields %>
  <tr>
    <td><%=h field.name %></td>
    <td><%=h field.code %></td>
    <td><%= link_to_unless field.map_url == '', 'Map', field.map_url %></td>
    <td><%=h field.location %></td>
    <% if @logged_in and @logged_in.update_site? %>
    <td><%= link_to 'Show', field %></td>
    <td><%= link_to 'Edit', edit_field_path(field) %></td>
    <td><%= link_to 'Destroy', field, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if @logged_in and @logged_in.update_site? %>
<%= link_to 'New field', new_field_path %>
<% end %>

app/views/fields/new.html.erb
<h1>New field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @field.name %>
</p>

<p>
  <b>Code:</b>
  <%= @field.code %>
</p>

<p>
  <b>Map:</b>
  <%= link_to_unless @field.map_url == '', 'View map', @field.map_url %>
</p>

<p>
  <b>Location:</b>
  <%= @field.location %>
</p>

<% if @logged_in %>
<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>
<% else %>
<%= link_to 'Back', season_games_path(:season_id => @season.id) %>
<% end %>